INSERT INTO products(id,gender,category,display_name) VALUES (15970,'Men','Topwear','Turtle Check Men Navy Blue Shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (39386,'Men','Bottomwear','Peter England Men Party Blue Jeans');
INSERT INTO products(id,gender,category,display_name) VALUES (59263,'Women','Watches','Titan Women Silver Watch');
INSERT INTO products(id,gender,category,display_name) VALUES (21379,'Men','Bottomwear','Manchester United Men Solid Black Track Pants');
INSERT INTO products(id,gender,category,display_name) VALUES (53759,'Men','Topwear','Puma Men Grey T-shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (1855,'Men','Topwear','Inkfruit Mens Chain Reaction T-shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (30805,'Men','Topwear','Fabindia Men Striped Green Shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (26960,'Women','Topwear','Jealous 21 Women Purple Shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (29114,'Men','Socks','Puma Men Pack of 3 Socks');
INSERT INTO products(id,gender,category,display_name) VALUES (30039,'Men','Watches','Skagen Men Black Watch');
INSERT INTO products(id,gender,category,display_name) VALUES (9204,'Men','Shoes','Puma Men Future Cat Remix SF Black Casual Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (48123,'Women','Belts','Fossil Women Black Huarache Weave Belt');
INSERT INTO products(id,gender,category,display_name) VALUES (18653,'Men','Flip Flops','Fila Men Cush Flex Black Slippers');
INSERT INTO products(id,gender,category,display_name) VALUES (47957,'Women','Bags','Murcia Women Blue Handbag');
INSERT INTO products(id,gender,category,display_name) VALUES (46885,'Boys','Flip Flops','Ben 10 Boys Navy Blue Slippers');
INSERT INTO products(id,gender,category,display_name) VALUES (12369,'Men','Topwear','Reid & Taylor Men Check Purple Shirts');
INSERT INTO products(id,gender,category,display_name) VALUES (29928,'Men','Watches','Police Men Black Dial Watch PL12889JVSB');
INSERT INTO products(id,gender,category,display_name) VALUES (42419,'Girls','Topwear','Gini and Jony Girls Knit White Top');
INSERT INTO products(id,gender,category,display_name) VALUES (51832,'Women','Innerwear','Bwitch Beige Full-Coverage Bra BW335');
INSERT INTO products(id,gender,category,display_name) VALUES (47359,'Women','Bags','Baggit Women Brown Handbag');
INSERT INTO products(id,gender,category,display_name) VALUES (17429,'Men','Watches','CASIO G-Shock Men Black Digital Watch G-7710-1DR G223');
INSERT INTO products(id,gender,category,display_name) VALUES (12967,'Men','Sandal','ADIDAS Men Spry M Black Sandals');
INSERT INTO products(id,gender,category,display_name) VALUES (6842,'Unisex','Shoe Accessories','Timberland Unisex Rubber Sole Brush Shoe Accessories');
INSERT INTO products(id,gender,category,display_name) VALUES (13089,'Men','Topwear','ADIDAS Men Lfc Auth Hood Grey Sweatshirts');
INSERT INTO products(id,gender,category,display_name) VALUES (18461,'Men','Fragrance','David Beckham Signature Men Deos');
INSERT INTO products(id,gender,category,display_name) VALUES (9036,'Men','Shoes','Buckaroo Men Flores Black Formal Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (48311,'Women','Jewellery','Pitaraa Women Bronze Beaded Bracelet');
INSERT INTO products(id,gender,category,display_name) VALUES (7990,'Men','Topwear','Fila Men''s Round Neck Navy Blue T-shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (56019,'Women','Lips','Colorbar Soft Touch Show Stopper Copper Lipstick 037');
INSERT INTO products(id,gender,category,display_name) VALUES (21977,'Women','Bags','Murcia Women Casual Brown Handbag');
INSERT INTO products(id,gender,category,display_name) VALUES (37812,'Men','Topwear','John Players Men Navy Blue Shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (4729,'Boys','Topwear','Disney Kids Boy''s Crew Sea Life Sialing Green Teen Kidswear');
INSERT INTO products(id,gender,category,display_name) VALUES (56825,'Men','Topwear','John Players Men Brown Shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (39988,'Men','Shoes','Gas Men Europa White Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (59051,'Women','Shoes','Carlton London Women Black & Gold Toned Flats');
INSERT INTO products(id,gender,category,display_name) VALUES (20099,'Women','Topwear','Diva Women Embroided Green Kurta');
INSERT INTO products(id,gender,category,display_name) VALUES (58183,'Women','Bags','Rocky S Women White Handbag');
INSERT INTO products(id,gender,category,display_name) VALUES (29742,'Women','Bags','Kiara Women Teal Handbag');
INSERT INTO products(id,gender,category,display_name) VALUES (51658,'Women','Watches','Fossil Women Copper Chronograph Watch CH2589');
INSERT INTO products(id,gender,category,display_name) VALUES (3954,'Women','Topwear','Jealous 21 Women''s Pink T-shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (18839,'Men','Belts','Peter England Men Formal Black Belt');
INSERT INTO products(id,gender,category,display_name) VALUES (2886,'Women','Shoes','Catwalk Women Leather Brown Flats');
INSERT INTO products(id,gender,category,display_name) VALUES (23278,'Men','Watches','Maxima Ssteele Men Off White Watch');
INSERT INTO products(id,gender,category,display_name) VALUES (28690,'Women','Topwear','W Women Printed Beige Kurta');
INSERT INTO products(id,gender,category,display_name) VALUES (8580,'Men','Topwear','Scullers Men  Grey Waistcoat');
INSERT INTO products(id,gender,category,display_name) VALUES (3168,'Men','Shoes','Nike Men''s Incinerate MSL White Blue Shoe');
INSERT INTO products(id,gender,category,display_name) VALUES (18005,'Men','Bottomwear','Puma Men Long Logo Black Bermuda');
INSERT INTO products(id,gender,category,display_name) VALUES (17871,'Men','Innerwear','Levis Men Boxer Maroon Brief');
INSERT INTO products(id,gender,category,display_name) VALUES (9452,'Men','Topwear','John Miller Men Stripes White Red Shirts');
INSERT INTO products(id,gender,category,display_name) VALUES (38402,'Women','Belts','Baggit Women Hood Dabang Black Belt');
INSERT INTO products(id,gender,category,display_name) VALUES (44984,'Women','Watches','Maxima Women White Dial Watch');
INSERT INTO products(id,gender,category,display_name) VALUES (10268,'Men','Shoes','Clarks Men Hang Work Leather Black Formal Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (45856,'Women','Topwear','Vishudh Women Brown Kurta');
INSERT INTO products(id,gender,category,display_name) VALUES (32138,'Men','Innerwear','Playboy Men Blue Titanium Briefs');
INSERT INTO products(id,gender,category,display_name) VALUES (59435,'Men','Shoes','Arrow Men Black Formal Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (5891,'Men','Topwear','Puma Men''s Stripe Polo Black T-shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (38630,'Women','Topwear','Nike Women Purple Polo T-shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (4943,'Men','Topwear','Gini and Jony Boy''s Kaleb White Brown Kidswear');
INSERT INTO products(id,gender,category,display_name) VALUES (11188,'Men','Watches','Carrera Men Dial steel finish strap Silver Watches');
INSERT INTO products(id,gender,category,display_name) VALUES (10866,'Men','Topwear','Wrangler Men Motor Rider Red T-Shirts');
INSERT INTO products(id,gender,category,display_name) VALUES (59607,'Women','Saree','FNF Pink & Grey Wedding Collection Sari');
INSERT INTO products(id,gender,category,display_name) VALUES (15528,'Men','Topwear','Puma Men Scribble Black Tshirts');
INSERT INTO products(id,gender,category,display_name) VALUES (45258,'Men','Watches','CASIO EDIFICE Men Black Dial Chronograph Watch ED60');
INSERT INTO products(id,gender,category,display_name) VALUES (42841,'Women','Bags','French Connection Women Beige Handbag');
INSERT INTO products(id,gender,category,display_name) VALUES (22198,'Men','Shoes','Timberland Men Black Casual Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (29570,'Men','Shoes','Vans Men Classic Slip-On Purple & Black Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (43993,'Women','Fragrance','Police Women Passion Perfume');
INSERT INTO products(id,gender,category,display_name) VALUES (6628,'Men','Shoes','ADIDAS Men''s Lowell White Silver Shoe');
INSERT INTO products(id,gender,category,display_name) VALUES (54924,'Men','Bottomwear','Do U Speak Green Men Blue Shorts');
INSERT INTO products(id,gender,category,display_name) VALUES (26538,'Men','Shoes','ID Men Red Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (35913,'Women','Bags','Peperone Women Black & White Handbag');
INSERT INTO products(id,gender,category,display_name) VALUES (49495,'Men','Shoes','Vans Men Khaki Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (9660,'Men','Topwear','Indigo Nation Men Reversible Bling Pink Shirts');
INSERT INTO products(id,gender,category,display_name) VALUES (2288,'Women','Topwear','Nike Women Black T-shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (23876,'Men','Topwear','ADIDAS Men Blue Sweatshirt');
INSERT INTO products(id,gender,category,display_name) VALUES (18237,'Men','Topwear','Manchester United Men Solid Red Tshirt');
INSERT INTO products(id,gender,category,display_name) VALUES (54118,'Women','Shoes','Rocia Women Black Flats');
INSERT INTO products(id,gender,category,display_name) VALUES (2872,'Women','Shoes','Catwalk Women Leather Flats');
INSERT INTO products(id,gender,category,display_name) VALUES (49653,'Women','Topwear','Mineral Women Green Top');
INSERT INTO products(id,gender,category,display_name) VALUES (8574,'Women','Sandal','Crocs Dora Boots Pink Sandals');
INSERT INTO products(id,gender,category,display_name) VALUES (16957,'Men','Eyewear','Image Men Sunglasses');
INSERT INTO products(id,gender,category,display_name) VALUES (19123,'Men','Flip Flops','Lotto Men XL Water Man Silver Slippers');
INSERT INTO products(id,gender,category,display_name) VALUES (13419,'Men','Topwear','United Colors of Benetton Men Solid Pink Polo T-shirts');
INSERT INTO products(id,gender,category,display_name) VALUES (17885,'Men','Innerwear','Levis Men Comfort Style Grey Innerwear Vest');
INSERT INTO products(id,gender,category,display_name) VALUES (43369,'Men','Flip Flops','Reebok Men Black Possession Flip Flops');
INSERT INTO products(id,gender,category,display_name) VALUES (48781,'Women','Jewellery','Lucera Women Silver Pendant');
INSERT INTO products(id,gender,category,display_name) VALUES (44970,'Men','Watches','Maxima Men White Dial Analog Chronograph Watch');
INSERT INTO products(id,gender,category,display_name) VALUES (56489,'Women','Nails','Streetwear Ash Nail Polish # 31');
INSERT INTO products(id,gender,category,display_name) VALUES (39524,'Unisex','Bags','Peter England Unisex Orange Sleeve Bag');
INSERT INTO products(id,gender,category,display_name) VALUES (33822,'Men','Shoes','Puma Men Axis White & Grey Sports Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (58513,'Women','Topwear','Tonga Women Maroon Top');
INSERT INTO products(id,gender,category,display_name) VALUES (25947,'Women','Scarves','Femella Women Brown Scarf');
INSERT INTO products(id,gender,category,display_name) VALUES (52029,'Unisex','Topwear','Just Natural Unisex Charcoal Rain Jacket');
INSERT INTO products(id,gender,category,display_name) VALUES (5865,'Men','Topwear','ADIDAS Men''s Twelve Faster T-shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (39716,'Women','Dress','Arrow Woman Women Blue Dress');
INSERT INTO products(id,gender,category,display_name) VALUES (25349,'Men','Innerwear','Levis Men Red Brief');
INSERT INTO products(id,gender,category,display_name) VALUES (11940,'Men','Sandal','Ganuchi Men Casual Black Sandals');
INSERT INTO products(id,gender,category,display_name) VALUES (55802,'Women','Loungewear and Nightwear','SDL by Sweet Dreams Women Green Printed Night Suit S11-3124');
INSERT INTO products(id,gender,category,display_name) VALUES (29584,'Men','Topwear','Indigo Nation Men Printed Black T-shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (43967,'Women','Fragrance','DKNY Women Red Delicious Perfume');
INSERT INTO products(id,gender,category,display_name) VALUES (28456,'Women','Bottomwear','Urban Yoga Women Blue Skirt With Leggings');
INSERT INTO products(id,gender,category,display_name) VALUES (34009,'Girls','Topwear','Gini and Jony Girls Black Top');
INSERT INTO products(id,gender,category,display_name) VALUES (19311,'Men','Shoes','Nike Men Air Rift MTR White Casual Shoe');
INSERT INTO products(id,gender,category,display_name) VALUES (42089,'Men','Shoes','ADIDAS Men White Corona Sports Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (22950,'Unisex','Watches','Fastrack Unisex Black Dial Watch 9915PP13');
INSERT INTO products(id,gender,category,display_name) VALUES (49461,'Men','Shoes','Vans Men Blue Era Scilla Plaid Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (8746,'Unisex','Flip Flops','Crocs Kids Navy Blue Clogs');
INSERT INTO products(id,gender,category,display_name) VALUES (9694,'Men','Topwear','Classic Polo Men Vulcan White Polo Tshirts');
INSERT INTO products(id,gender,category,display_name) VALUES (23882,'Men','Shoes','Fila Men Destiny Grey Sports Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (34835,'Men','Shoes','ADIDAS Men Blue Chill Sports Shoes');
INSERT INTO products(id,gender,category,display_name) VALUES (15984,'Men','Topwear','Turtle Check Men Yellow Shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (41268,'Men','Wallets','Arrow Men Black Wallet');
INSERT INTO products(id,gender,category,display_name) VALUES (11518,'Women','Shoes','Catwalk Women Gun Metal Grey Heels');
INSERT INTO products(id,gender,category,display_name) VALUES (14856,'Women','Wallets','United Colors of Benetton Women Solid Beige Wallets');
INSERT INTO products(id,gender,category,display_name) VALUES (33648,'Men','Sandal','Lotto Men Ridge Brown Sandals');
INSERT INTO products(id,gender,category,display_name) VALUES (59297,'Men','Topwear','U.S. Polo Assn. Men White & Navy Blue Shirt');
INSERT INTO products(id,gender,category,display_name) VALUES (28032,'Men','Innerwear','Jockey ELANCE Men Bikini White Brief 1005');
INSERT INTO products(id,gender,category,display_name) VALUES (27846,'Women','Topwear','Scullers For Her Charcoal Blazer');
INSERT INTO products(id,gender,category,display_name) VALUES (26994,'Women','Bottomwear','Jealous 21 Women Black Jeans');
