INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (15970,'Men','Topwear','Turtle Check Men Navy Blue Shirt',81992,8,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (39386,'Men','Bottomwear','Peter England Men Party Blue Jeans',53778,18,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (59263,'Women','Watches','Titan Women Silver Watch',20187,16,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (21379,'Men','Bottomwear','Manchester United Men Solid Black Track Pants',46129,9,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (53759,'Men','Topwear','Puma Men Grey T-shirt',37964,5,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (1855,'Men','Topwear','Inkfruit Mens Chain Reaction T-shirt',42146,16,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (30805,'Men','Topwear','Fabindia Men Striped Green Shirt',61992,9,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (26960,'Women','Topwear','Jealous 21 Women Purple Shirt',18371,18,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (29114,'Men','Socks','Puma Men Pack of 3 Socks',40709,12,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (30039,'Men','Watches','Skagen Men Black Watch',14427,17,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (9204,'Men','Shoes','Puma Men Future Cat Remix SF Black Casual Shoes',85638,9,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (48123,'Women','Belts','Fossil Women Black Huarache Weave Belt',28464,14,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (18653,'Men','Flip Flops','Fila Men Cush Flex Black Slippers',90269,8,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (47957,'Women','Bags','Murcia Women Blue Handbag',96626,15,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (46885,'Boys','Flip Flops','Ben 10 Boys Navy Blue Slippers',87752,10,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (12369,'Men','Topwear','Reid & Taylor Men Check Purple Shirts',72200,12,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (29928,'Men','Watches','Police Men Black Dial Watch PL12889JVSB',53969,11,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (42419,'Girls','Topwear','Gini and Jony Girls Knit White Top',41544,5,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (51832,'Women','Innerwear','Bwitch Beige Full-Coverage Bra BW335',26656,19,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (47359,'Women','Bags','Baggit Women Brown Handbag',14192,14,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (17429,'Men','Watches','CASIO G-Shock Men Black Digital Watch G-7710-1DR G223',89432,6,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (12967,'Men','Sandal','ADIDAS Men Spry M Black Sandals',39840,7,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (6842,'Unisex','Shoe Accessories','Timberland Unisex Rubber Sole Brush Shoe Accessories',23725,6,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (13089,'Men','Topwear','ADIDAS Men Lfc Auth Hood Grey Sweatshirts',59407,17,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (18461,'Men','Fragrance','David Beckham Signature Men Deos',26379,15,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (9036,'Men','Shoes','Buckaroo Men Flores Black Formal Shoes',66207,16,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (48311,'Women','Jewellery','Pitaraa Women Bronze Beaded Bracelet',11555,14,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (7990,'Men','Topwear','Fila Men''s Round Neck Navy Blue T-shirt',55743,10,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (56019,'Women','Lips','Colorbar Soft Touch Show Stopper Copper Lipstick 037',22703,14,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (21977,'Women','Bags','Murcia Women Casual Brown Handbag',87789,9,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (37812,'Men','Topwear','John Players Men Navy Blue Shirt',86555,20,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (4729,'Boys','Topwear','Disney Kids Boy''s Crew Sea Life Sialing Green Teen Kidswear',47717,6,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (56825,'Men','Topwear','John Players Men Brown Shirt',60752,5,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (39988,'Men','Shoes','Gas Men Europa White Shoes',81679,20,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (59051,'Women','Shoes','Carlton London Women Black & Gold Toned Flats',18341,18,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (20099,'Women','Topwear','Diva Women Embroided Green Kurta',74071,13,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (58183,'Women','Bags','Rocky S Women White Handbag',32899,11,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (29742,'Women','Bags','Kiara Women Teal Handbag',99440,14,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (51658,'Women','Watches','Fossil Women Copper Chronograph Watch CH2589',63232,19,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (3954,'Women','Topwear','Jealous 21 Women''s Pink T-shirt',39717,7,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (18839,'Men','Belts','Peter England Men Formal Black Belt',56574,13,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (2886,'Women','Shoes','Catwalk Women Leather Brown Flats',58649,7,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (23278,'Men','Watches','Maxima Ssteele Men Off White Watch',97105,18,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (28690,'Women','Topwear','W Women Printed Beige Kurta',37960,6,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (8580,'Men','Topwear','Scullers Men  Grey Waistcoat',78333,20,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (3168,'Men','Shoes','Nike Men''s Incinerate MSL White Blue Shoe',25519,16,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (18005,'Men','Bottomwear','Puma Men Long Logo Black Bermuda',63341,13,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (17871,'Men','Innerwear','Levis Men Boxer Maroon Brief',53534,14,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (9452,'Men','Topwear','John Miller Men Stripes White Red Shirts',50328,17,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (38402,'Women','Belts','Baggit Women Hood Dabang Black Belt',31037,16,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (44984,'Women','Watches','Maxima Women White Dial Watch',84512,6,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (10268,'Men','Shoes','Clarks Men Hang Work Leather Black Formal Shoes',10310,17,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (45856,'Women','Topwear','Vishudh Women Brown Kurta',37750,13,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (32138,'Men','Innerwear','Playboy Men Blue Titanium Briefs',79730,17,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (59435,'Men','Shoes','Arrow Men Black Formal Shoes',33907,7,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (5891,'Men','Topwear','Puma Men''s Stripe Polo Black T-shirt',81928,19,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (38630,'Women','Topwear','Nike Women Purple Polo T-shirt',89958,12,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (4943,'Men','Topwear','Gini and Jony Boy''s Kaleb White Brown Kidswear',74958,12,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (11188,'Men','Watches','Carrera Men Dial steel finish strap Silver Watches',76939,6,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (10866,'Men','Topwear','Wrangler Men Motor Rider Red T-Shirts',58413,11,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (59607,'Women','Saree','FNF Pink & Grey Wedding Collection Sari',75975,14,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (15528,'Men','Topwear','Puma Men Scribble Black Tshirts',98193,11,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (45258,'Men','Watches','CASIO EDIFICE Men Black Dial Chronograph Watch ED60',81866,6,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (42841,'Women','Bags','French Connection Women Beige Handbag',32262,6,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (22198,'Men','Shoes','Timberland Men Black Casual Shoes',99615,18,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (29570,'Men','Shoes','Vans Men Classic Slip-On Purple & Black Shoes',93294,20,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (43993,'Women','Fragrance','Police Women Passion Perfume',72648,20,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (6628,'Men','Shoes','ADIDAS Men''s Lowell White Silver Shoe',59617,7,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (54924,'Men','Bottomwear','Do U Speak Green Men Blue Shorts',40790,16,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (26538,'Men','Shoes','ID Men Red Shoes',24788,9,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (35913,'Women','Bags','Peperone Women Black & White Handbag',17776,20,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (49495,'Men','Shoes','Vans Men Khaki Shoes',33604,17,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (9660,'Men','Topwear','Indigo Nation Men Reversible Bling Pink Shirts',42955,7,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (2288,'Women','Topwear','Nike Women Black T-shirt',28177,14,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (23876,'Men','Topwear','ADIDAS Men Blue Sweatshirt',96872,14,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (18237,'Men','Topwear','Manchester United Men Solid Red Tshirt',75484,15,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (54118,'Women','Shoes','Rocia Women Black Flats',33780,9,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (2872,'Women','Shoes','Catwalk Women Leather Flats',94306,11,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (49653,'Women','Topwear','Mineral Women Green Top',12910,5,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (8574,'Women','Sandal','Crocs Dora Boots Pink Sandals',22028,18,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (16957,'Men','Eyewear','Image Men Sunglasses',30154,6,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (19123,'Men','Flip Flops','Lotto Men XL Water Man Silver Slippers',71756,7,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (13419,'Men','Topwear','United Colors of Benetton Men Solid Pink Polo T-shirts',30031,16,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (17885,'Men','Innerwear','Levis Men Comfort Style Grey Innerwear Vest',20811,17,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (43369,'Men','Flip Flops','Reebok Men Black Possession Flip Flops',42725,6,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (48781,'Women','Jewellery','Lucera Women Silver Pendant',68329,18,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (44970,'Men','Watches','Maxima Men White Dial Analog Chronograph Watch',51997,13,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (56489,'Women','Nails','Streetwear Ash Nail Polish # 31',47655,5,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (39524,'Unisex','Bags','Peter England Unisex Orange Sleeve Bag',94356,17,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (33822,'Men','Shoes','Puma Men Axis White & Grey Sports Shoes',32564,18,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (58513,'Women','Topwear','Tonga Women Maroon Top',83688,6,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (25947,'Women','Scarves','Femella Women Brown Scarf',82320,7,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (52029,'Unisex','Topwear','Just Natural Unisex Charcoal Rain Jacket',35593,8,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (5865,'Men','Topwear','ADIDAS Men''s Twelve Faster T-shirt',79169,15,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (39716,'Women','Dress','Arrow Woman Women Blue Dress',50780,16,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (25349,'Men','Innerwear','Levis Men Red Brief',31790,9,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (11940,'Men','Sandal','Ganuchi Men Casual Black Sandals',10810,5,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (55802,'Women','Loungewear and Nightwear','SDL by Sweet Dreams Women Green Printed Night Suit S11-3124',52873,17,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (29584,'Men','Topwear','Indigo Nation Men Printed Black T-shirt',65277,14,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (43967,'Women','Fragrance','DKNY Women Red Delicious Perfume',24818,7,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (28456,'Women','Bottomwear','Urban Yoga Women Blue Skirt With Leggings',74869,5,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (34009,'Girls','Topwear','Gini and Jony Girls Black Top',88242,5,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (19311,'Men','Shoes','Nike Men Air Rift MTR White Casual Shoe',34366,13,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (42089,'Men','Shoes','ADIDAS Men White Corona Sports Shoes',36110,8,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (22950,'Unisex','Watches','Fastrack Unisex Black Dial Watch 9915PP13',32396,12,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (49461,'Men','Shoes','Vans Men Blue Era Scilla Plaid Shoes',40783,8,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (8746,'Unisex','Flip Flops','Crocs Kids Navy Blue Clogs',14427,10,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (9694,'Men','Topwear','Classic Polo Men Vulcan White Polo Tshirts',10182,16,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (23882,'Men','Shoes','Fila Men Destiny Grey Sports Shoes',11860,7,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (34835,'Men','Shoes','ADIDAS Men Blue Chill Sports Shoes',33795,12,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (15984,'Men','Topwear','Turtle Check Men Yellow Shirt',59796,20,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (41268,'Men','Wallets','Arrow Men Black Wallet',90915,5,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (11518,'Women','Shoes','Catwalk Women Gun Metal Grey Heels',71155,9,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (14856,'Women','Wallets','United Colors of Benetton Women Solid Beige Wallets',99398,17,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (33648,'Men','Sandal','Lotto Men Ridge Brown Sandals',22857,15,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (59297,'Men','Topwear','U.S. Polo Assn. Men White & Navy Blue Shirt',61600,17,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (28032,'Men','Innerwear','Jockey ELANCE Men Bikini White Brief 1005',59130,13,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (27846,'Women','Topwear','Scullers For Her Charcoal Blazer',76659,16,TRUE);
INSERT INTO products(id,gender,category,display_name,price,stock,is_active) VALUES (26994,'Women','Bottomwear','Jealous 21 Women Black Jeans',44463,13,TRUE);
